
{{- range .Values.externalSecrets}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-vault
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
{{- range .data }}
  - secretKey: {{ .key }}
    remoteRef:
      key: {{ .remoteKey }}
{{- end }}
{{- end }}